version: '2'

services:
  almedia-task:
    image: almedia-task
    build: .
    env_file: .env
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: "mariadb"
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_PASSWORD: password
      MARIADB_USER: user
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
